### ISSUE TITLE
enhancement - provide slim version for cocopods

### ISSUE THREAD

**Issue by wwe-johndpope** [zixun/GodEye#14]
I want to use this in project - but there's too many sub pod dependencies.
eg. I just want logging. 
It would be great to not have to include everything / just to use the in app logging.  (eg. sqlite logging stuff)

**Comment by wwe-johndpope** [comment]
reverting to Dotzu / the logging seems very unstable when used in conjunction with nserror.localizedDescription

**Comment by zixun** [comment]
Thanks for you feedback! if you just want in app logging, [TinyConsole](https://github.com/Cosmo/TinyConsole) will be more suitable。

and can you provide more detail about use with nserror.localizedDescription

**Comment by johndpope** [comment]
thanks - the code I had which was causing a crash is tangled up in Alamofire. 

It was initially all working fine  - but suddenly became unstable with sqlite / threading stuff. 
Unfortunately - I binned code. I was using SDWebImage in conjunction which may have not played nicely. sorry can't be more help - it seems like it was honking out trying to do an insert.

     
          doStuff(videoItem: videoItem) { (success, result, error) in
                
                guard let successResult = result, error == nil && success == true else {
                   
                    Log4g.error(error?.localizedDescription) // this was causing logger to crash...
                    return
                }


<img width="377" alt="screen shot 2017-03-15 at 2 02 30 pm" src="https://cloud.githubusercontent.com/assets/289994/23999324/6caef3c0-0a2e-11e7-8b5a-26a36eca73fe.png">

**Comment by wwe-johndpope** [comment]
you may be able to trip it up with airline mode. I think the swagger API was hitting rate limits.

**Comment by zixun** [comment]
@johndpope can see any crash log in crash print console。
and by the way,please upgrade the version of GodEye to `1.0.2`,it fix a bug about `SIGNAL` crash not display~
