### ISSUE TITLE
pod 'GodEye' 出错

### ISSUE THREAD

**Issue by dev4shane** [zixun/GodEye#16]
Unable to find a specification for `AppBaseKit` depended upon by `GodEye`

**Comment by zixun** [comment]
试试运行下 `pod repo update`

**Comment by crossle** [comment]
不知道为啥，pod search 居然搜不到，  pod 'GodEye', :git => 'git@github.com:zixun/GodEye.git'
只好先这样了

**Comment by zixun** [comment]
@crossle 搜不到没关系，可以直接`pod 'GodEye'` 然后`pod update`, 我也搜不到，但是可以正常集成，很奇怪，不知道为啥=。=

**Comment by crossle** [comment]
奇怪的是 Cocoapods 网站可以搜到

**Comment by zixun** [comment]
嗯，是的，感觉是Cocoapods的bug

**Comment by zixun** [comment]
@crossle  删除掉`~/Library/Caches/CocoaPods/search_index.json`就可以了。

[https://github.com/CocoaPods/CocoaPods/issues/5172](https://github.com/CocoaPods/CocoaPods/issues/5172)
