### ISSUE TITLE
关于demo

### ISSUE THREAD

**Issue by Wbqqqq** [zixun/GodEye#21]
关于这个demo的问题，我clone之后，pod 和  convert之后  pod文件中有几个是需要修改的， 修改之后报了这个错。
![645dd68d-3e15-491f-9ce4-b93b288bd2c5](https://cloud.githubusercontent.com/assets/17332298/24251056/d1a0bab2-1013-11e7-9ecc-274e8d032bb5.png)

**Comment by zixun** [comment]
照道理说是不需要convert，因为我用的swift版本是最新的，你的Xcode的版本是多少

**Comment by Wbqqqq** [comment]
8.2.1

**Comment by Wbqqqq** [comment]
其中的一些pod文件 需要convert  我不得不unlock一下

**Comment by zixun** [comment]
我也是8.2.1，好像没出现需要convert的情况啊

**Comment by zixun** [comment]
要convert的代码能截个图我看看嘛

**Comment by Wbqqqq** [comment]
![Uploading D3997F86-72BA-450F-964D-2C526AFDF100.png…]()

**Comment by Wbqqqq** [comment]
![Uploading D3997F86-72BA-450F-964D-2C526AFDF100.png…]()

**Comment by Wbqqqq** [comment]
发你邮箱吧，图一直传不上。

**Comment by zixun** [comment]
@Wbqqqq 小伙子，图挂了

**Comment by zixun** [comment]
已帮你更新图，是不是你的工程不是用最新的Swift版本编译的，你试试新建一个工程，引入GodEye看

**Comment by Wbqqqq** [comment]
试了 好像还是不行， 不过cocochina的demo我可以玩，已经在看了，很神奇。 新的测试工程只是单纯的pod了godeye，进工程还是需要convert，难道是我哪里配置不对。

**Comment by zixun** [comment]
@Wbqqqq 我这边新工程也会出现convert，我看下应该是个bug

**Comment by Wbqqqq** [comment]
ok

**Comment by zixun** [comment]
@Wbqqqq  找到原因了，[https://github.com/CocoaPods/CocoaPods/issues/5864#issuecomment-247109685](https://github.com/CocoaPods/CocoaPods/issues/5864#issuecomment-247109685).cocoapods需要在trunk前执行下`echo "3.0" > .swift-version`告诉cocoapods这个库是用swift哪个版本，不然`Use Legacy Swift Language Version`会变成`Unspecified`


CocoaChinaPlus因为在`Podfile`里写了：

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```
将所有的pod库都指定成了3.0，所以不会有问题。 我后续逐个库更新下版本修复掉这个问题，你可以按照CocoaChinaPlus的方式先玩起来

**Comment by Wbqqqq** [comment]
所噶！ 老哥稳
