### ISSUE TITLE
[Xcode8.3] Build Failed

### ISSUE THREAD

**Issue by ibadcool** [zixun/GodEye#23]
![Uploading AAD11598-67F1-4A07-8F73-F6C4E61EB531.png…]()
XCode8.3 编译失败, 依赖的 SQLite.swift 的问题

**Comment by zixun** [comment]
@ibadcool  图挂了 少年

**Comment by ibadcool** [comment]
@zixun Sorry.
Error:
Lexical or Preprocessor Issue Group
  /Users/Sunny/Desktop/LottieAnimation/Pods/SQLite.swift/Sources/SQLiteObjc/fts3_tokenizer.h:27:9: 'sqlite3.h' file not found
In file included from /Users/Sunny/Desktop/Test/Pods/SQLite.swift/Sources/SQLiteObjc/SQLite-Bridging.m:26:9: In file included from /Users/Sunny/Desktop/Test/Pods/SQLite.swift/Sources/SQLiteObjc/SQLite-Bridging.m:26:

**Comment by rainedAllNight** [comment]
一样，10.3Example编译失败
![b1ee0896-3dcd-4a9a-bf94-476fd24116d9](https://cloud.githubusercontent.com/assets/16357931/24440733/65809626-1488-11e7-8e97-4fb487fe145b.png)

**Comment by zixun** [comment]
@rainedAllNight 你这个是你的证书问题

**Comment by zixun** [comment]
@ibadcool 你是OC的工程？

**Comment by rainedAllNight** [comment]
。。我要自戳双眼了。。

**Comment by ibadcool** [comment]
@zixun  混编的

**Comment by ibadcool** [comment]
@zixun 找到原因了,我工程里同时用了 GRDB这个库...然后跟 SQLite.swift 冲突.. 删了GRDB 就好了.
可是我又得用GRDB.. 这咋解决?

**Comment by zixun** [comment]
@ibadcool  这个我觉得你还是问一下SQLite.swift的作者，GodEye这层目前肯定是解决不了

**Comment by zixun** [comment]
@ibadcool 后续我打算把SQLite.swift这个依赖库去掉，这个库太大了，想自己用sqlite裸写数据操作，不过目前优先级没那么高

**Comment by zixun** [comment]
@ibadcool  如果你对sqlite3.0的api熟悉的话也欢迎提PR给我

**Comment by ibadcool** [comment]
@zixun 嗯, 支持大神.我就是个菜鸟,只能用用你们这些大神写的库了.
我去问问SQLite.swift 有没有办法. 多谢了

**Comment by Marcusias** [comment]
请问解决了么,我混编也遇到了这个问题

**Comment by zixun** [comment]
SQLite.swift已经可以编译
