### ISSUE TITLE
Use sqlite3.0 replace dependency of SQLite.swift

### ISSUE THREAD

**Issue by zixun** [zixun/GodEye#24]
I found `SQLite.swift` is so huge and  it‘s unsuited for GodEye. such as [https://github.com/zixun/GodEye/issues/22](https://github.com/zixun/GodEye/issues/22).

so, in the next version of GodEye, I will Use sqlite3.0 without any dependency to replace the dependency of SQLite.swift

**Comment by zixun** [comment]
[https://github.com/zixun/GodEye/issues/22](https://github.com/zixun/GodEye/issues/22)

**Comment by jeffreylyg** [comment]
@zixun 大概什么时候发下个版本呀？

**Comment by zixun** [comment]
今天刚发了一个小版本，修复了一些近期反馈的bug，下个版本移除`SQLite.swift`工程量有点大，打算尽量4月底前搞定

**Comment by zixun** [comment]
this feature will be developed in branch of [https://github.com/zixun/GodEye/tree/feature/sqlite3.0](https://github.com/zixun/GodEye/tree/feature/sqlite3.0)

**Comment by zixun** [comment]
I found use sqlite3.0 in swift is very complex and SQLite.swift do it well.
and the bug of [https://github.com/zixun/GodEye/issues/22](https://github.com/zixun/GodEye/issues/22) is an error cased by my demo project, I have adjusted the project, and the demo can work well

so, this enhancement will be cancle
