### ISSUE TITLE
Demo 在xcode8.3.1运行不起来啊！

### ISSUE THREAD

**Issue by devilon** [zixun/GodEye#28]
Demo 在xcode8.3.1运行不起来啊！报错找不到sqlite
![wx20170414-171746](https://cloud.githubusercontent.com/assets/9944101/25039493/681172ba-2136-11e7-8255-572383f5a233.png)

**Comment by hstdt** [comment]
这里编译不过去+1。
新建的项目，全部默认，最低版本号是10.3。
pod从1.0.2到1.1.2都试过了。1.0.0回不去。
![image](https://cloud.githubusercontent.com/assets/10215098/25041084/fed6edca-213f-11e7-9e86-1b6dd9fe80e5.png)

**Comment by JustinM1** [comment]
@hstdt You can go to pods/SQLite, Deployment Info and change deployment target to 8.0. I use Fastlane so I had to fork the repo and change the podfile deployment target to 9.0

**Comment by hstdt** [comment]
@zixun SQLite.swift 0.11.3最低系统版本变成了iOS9，和GodEye的iOS8冲突了，希望可以把podspec中依赖库改成`s.dependency 'SQLite.swift', '= 0.11.2'`。不然即使我自己设置成最低版本iOS9也是无法通过编译的。

因为我对另外2个依赖库不熟，所以也不好意思就这个不齐全的改动提一个pull，暂时就自己Fork一份改了下。

```
pod 'GodEye', :git => 'https://github.com/hstdt/GodEye.git', :branch => 'master'
```

**Comment by zhouzichao0709** [comment]
+1

**Comment by zhouzichao0709** [comment]
@zixun

**Comment by liz123cn** [comment]
+1

**Comment by PandaraWen** [comment]
是不再维护了吗

**Comment by zixun** [comment]
@PandaraWen 最近有些事在忙，对不住各位，马上忙完了，过段时间立马更新

**Comment by zixun** [comment]
SQLite.swift已解决了它的编译问题
