### ISSUE TITLE
Network模块没有数据

### ISSUE THREAD

**Issue by BMMax** [zixun/GodEye#31]
网络使用gzip, network模块中没有相应请求响应数据数据

**Comment by zixun** [comment]
@BMMax gzip不是用来压缩打包的么？

**Comment by RhastaLi** [comment]
@zixun 使用截屏分享崩溃，并且 重启app 以后 god eye的 几个log模块均不能工作

**Comment by zixun** [comment]
@RhastaLi 有崩溃的堆栈吗
