### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by JunyiXie** [zixun/GodEye#32]
dyld: Library not loaded: @rpath/GodEye.framework/GodEye
  Referenced from: /var/containers/Bundle/Application/0BE59DC4-710C-4D79-ACC9-3B449ACE1E3A/GodEye_Example.app/GodEye_Example
  Reason: image not found

运行后，崩溃啊

**Comment by zixun** [comment]
真机还是模拟器

**Comment by applejian** [comment]
真机吧

**Comment by zixun** [comment]
没有复现,先close,如有问题可以reopen联系我
