### ISSUE TITLE
cocopods 导入报错，ESPullToRefresh 问题

### ISSUE THREAD

**Issue by WHaveFun** [zixun/GodEye#38]
是ESPullToRefresh 更新了？
Value of type 'RecordTableView' has no member 'es_addPullToRefresh'
<img width="995" alt="2018-04-02 7 44 01" src="https://user-images.githubusercontent.com/13980779/38195118-63a5f1fe-36ae-11e8-87a5-a51cb982e3e9.png">

**Comment by zixun** [comment]
已适配5.0
