### ISSUE TITLE
CPU超过100%问题

### ISSUE THREAD

**Issue by MoShenGuo** [zixun/GodEye#43]
你好  计算APP占用率:
  /// Get CPU usage of application,get from all thread
    open class func applicationUsage() -> Double {
        let threads = self.threadBasicInfos()
        var result : Double = 0.0
        threads.forEach { (thread:thread_basic_info) in
            if self.flag(thread) {
                result += Double.init(thread.cpu_usage) / Double.init(TH_USAGE_SCALE);
            }
        }
        return result * 100
    }
这个方法计算出来CPU占用率有超过100% 这是正确情况吗

**Comment by zixun** [comment]
应该没有问题,cpu过载的情况下是会出现的
