### ISSUE TITLE
Conflict with FMDB

### ISSUE THREAD

**Issue by hstdt** [zixun/GodEye#7]
里面的SQLite.swift或许和FMDB冲突了.installing之后FMDB就报错了.
另外吐槽一下,这里面带的东西好多,怎么还有MJRefresh

![image](https://cloud.githubusercontent.com/assets/10215098/23887064/5686dc86-08ba-11e7-8038-aeb1e908696e.png)

**Comment by zixun** [comment]
因为实际环境下，比如日志，数据量会比较大，因此日志内容展示做了分页处理，这样就需要上拉加载下一页，而历史数据又需要下拉加载上一页，因此引入了MJRefresh。
SQLite.swift和FMDB冲突我还没遇到过，能详细说一下吗

**Comment by hstdt** [comment]
@zixun 
我的,定位问题错了,修正一下, `SQLite.swift`这样改了就可以通过编译了.

Xcode8.2.1

![image](https://cloud.githubusercontent.com/assets/10215098/23887369/74e48938-08bc-11e7-9b49-1b09c734a9af.png)

修改前

![image](https://cloud.githubusercontent.com/assets/10215098/23887393/96a99356-08bc-11e7-95eb-9e473d667cc7.png)

**Comment by zixun** [comment]
good job! 可以反馈给SQLite.swift的作者，他那边更新后我这边更新下依赖版本就好
