### ISSUE TITLE
摇动手机会崩溃

### ISSUE THREAD

**Issue by duzexu** [zixun/GodEye#9]
错误是
 -[UIView app_motionEnded:with:]: unrecognized selector
打印self不是uiwindow而是view
![7f67f545-b871-48fd-bbe1-79bdbcd49988](https://cloud.githubusercontent.com/assets/4484464/23889342/970d9670-08c7-11e7-97ac-9b448ce25b8d.png)

**Comment by zixun** [comment]
感谢反馈，下班后我看一下

**Comment by zixun** [comment]
已解决
